In [1]:
import numpy as np

In [35]:
arr=np.array([[78,85,90],[45,60,55],[88,92,95],[30,40,35],[65,70,75]]);
print(arr)

[[78 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]


task1

In [3]:
print(arr.shape);

(5, 3)


In [4]:
#total number of elements
print(arr.size);    
print(arr.dtype)

15
int64


In [5]:
print(arr[1]);

[45 60 55]


In [6]:
print(arr[:,1]);

[85 60 92 40 70]


task2

In [10]:
print(np.average(arr,axis=1));
print(np.average(arr,axis=0));

[84.33333333 53.33333333 91.66666667 35.         70.        ]
[61.2 69.4 70. ]


task3

In [14]:
print(np.average(arr>=80,axis=1));

[0.66666667 0.         1.         0.         0.        ]


task4

In [17]:
#pass =1 and fail=0
print(np.where(arr>=50,1,0));

[[1 1 1]
 [0 1 1]
 [1 1 1]
 [0 0 0]
 [1 1 1]]


task5

In [19]:
print(np.where(arr<40,0,arr));

[[78 85 90]
 [45 60 55]
 [88 92 95]
 [ 0 40  0]
 [65 70 75]]


task5

In [27]:
row_avg = np.mean(arr, axis=1)

grades = np.where(
    row_avg > 80, "Grade A",
    np.where(row_avg > 70, "Grade B", "No Grade")
)

print("Row averages:", row_avg)
print("Grades:", grades)


Row averages: [84.33333333 53.33333333 91.66666667 35.         70.        ]
Grades: ['Grade A' 'No Grade' 'Grade A' 'No Grade' 'No Grade']


In [37]:
copied = arr.copy()   # independent copy
arr[:] = 0            # change ONLY original

print("Original array:", arr)
print("Copied array:", copied)

Original array: [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
Copied array: [[78 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]
