q1

In [1]:
#a university electricity usage (in units) of 4 hostels over 7 days(mon and sun)
#shape =(4,7)
#rows=hostel1,hostel2,hostel3,hostel4
#columns=mon,tue,wed,thu,fri,sat,sun
import numpy as np
elec=np.random.randint(120,650,size=(4,7));
print(elec);

[[543 597 624 177 235 201 518]
 [647 449 262 225 394 389 354]
 [380 613 517 569 445 542 172]
 [384 196 369 303 208 131 314]]


In [5]:
print(elec.shape);
print(elec.ndim);
print(elec.size);
print(elec.dtype);

(4, 7)
2
28
int32
