q1

In [3]:
#a university electricity usage (in units) of 4 hostels over 7 days(mon and sun)
#shape =(4,7)
#rows=hostel1,hostel2,hostel3,hostel4
#columns=mon,tue,wed,thu,fri,sat,sun
import numpy as np
elec=np.random.randint(120,650,size=(4,7));
print(elec);

[[603 502 149 151 567 262 539]
 [324 333 336 453 620 636 342]
 [381 381 186 635 178 281 164]
 [345 542 179 152 449 567 218]]


In [4]:
print(elec.shape);
print(elec.ndim);
print(elec.size);
print(elec.dtype);

(4, 7)
2
28
int32


In [5]:
import numpy as np

In [7]:
#find the average,maximum electricity usage per hostel and identify hostel with highest average usage

avg_usage = np.mean(elec, axis=1)
print("\nAverage usage per hostel:", avg_usage)

highest_avg_index = np.argmax(avg_usage)

print("\nHostel with highest average usage: Hostel", highest_avg_index + 1)
print("Highest average value:", avg_usage[highest_avg_index])


Average usage per hostel: [396.14285714 434.85714286 315.14285714 350.28571429]

Hostel with highest average usage: Hostel 2
Highest average value: 434.85714285714283


In [ ]:
#caluclate electricity consumption per day and identify the highest
daily_total = np.sum(elec, axis=0)

print("\nTotal electricity consumption per day:")
print(daily_total)

highest_day_index = np.argmax(daily_total)

days = ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"]

print("\nDay with highest consumption:", days[highest_day_index])
print("Highest consumption value:", daily_total[highest_day_index])

In [8]:
#if electricity usage on any day is greater than 550 unite a 20% surcharge is applied
 # create a new array penalized usage such  that: 
#   value >550->multiplied by 1.20
#   all other values remain unchanged
penalized_usage = np.where(elec > 550, elec * 1.20, elec)

print("\nPenalized Usage:\n", penalized_usage)



Penalized Usage:
 [[723.6 502.  149.  151.  680.4 262.  539. ]
 [324.  333.  336.  453.  744.  763.2 342. ]
 [381.  381.  186.  762.  178.  281.  164. ]
 [345.  542.  179.  152.  449.  680.4 218. ]]


In [9]:
#compare each hostels daily usage with its own weekly average. create a boolean matrix where:
#true=above hostel avg
#false=below or equal to hostel average
weekly_avg = np.mean(elec, axis=1)

print("\nWeekly Average per Hostel:\n", weekly_avg)
weekly_avg = weekly_avg.reshape(4,1)
comparison = elec > weekly_avg

print("\nBoolean Matrix (True = above avg, False = below/equal):\n")
print(comparison)



Weekly Average per Hostel:
 [396.14285714 434.85714286 315.14285714 350.28571429]

Boolean Matrix (True = above avg, False = below/equal):

[[ True  True False False  True False  True]
 [False False False  True  True  True False]
 [ True  True False  True False False False]
 [False  True False False  True  True False]]


In [ ]:
#reshape the electricity daata into single row representing weekly usage (shape: 1 x28)
# reshape the same data into 2 rows and 14 columns. ensure no data is lost or duplicated


elec = np.random.randint(120,650,size=(4,7))
print("Original Shape:", elec.shape)

single_row = elec.reshape(1,28)

print("\nReshaped to (1,28):")
print(single_row)
print("New Shape:", single_row.shape)


two_rows = elec.reshape(2,14)

print("\nReshaped to (2,14):")
print(two_rows)
print("New Shape:", two_rows.shape)



In [12]:
# #create ref_backup = electricity
# #create safe_backup=elecatricity.copy()
# modify one value in the original electricity array
#obsereve which backup change


electricity = np.random.randint(120,650,size=(4,7))

print("Original Electricity:\n", electricity)
# Reference backup
ref_backup = electricity

# Safe copy backup
safe_backup = electricity.copy()

# Modify one value in original array
electricity[0,0] = 9999

print("\nModified Original Electricity:\n", electricity)

print("\nReference Backup:\n", ref_backup)

print("\nSafe Backup:\n", safe_backup)

Original Electricity:
 [[312 284 568 266 179 228 468]
 [465 544 598 580 432 442 501]
 [535 630 607 136 621 352 614]
 [501 540 445 544 283 298 558]]

Modified Original Electricity:
 [[9999  284  568  266  179  228  468]
 [ 465  544  598  580  432  442  501]
 [ 535  630  607  136  621  352  614]
 [ 501  540  445  544  283  298  558]]

Reference Backup:
 [[9999  284  568  266  179  228  468]
 [ 465  544  598  580  432  442  501]
 [ 535  630  607  136  621  352  614]
 [ 501  540  445  544  283  298  558]]

Safe Backup:
 [[312 284 568 266 179 228 468]
 [465 544 598 580 432 442 501]
 [535 630 607 136 621 352 614]
 [501 540 445 544 283 298 558]]
