In [1]:
# hello

print("Hello world")

Hello world


Task 2.1 --

In [1]:
import numpy as np

In [6]:
mat=np.array([[1,2,3],[4,56,6]]);
print(mat);

[[ 1  2  3]
 [ 4 56  6]]


In [2]:
arr=np.array([100,200,300]);
arr=arr*2;
print(arr);

[200 400 600]


In [5]:
print(arr*mat);

[[  200   800  1800]
 [  800 22400  3600]]


In [7]:
print(np.sqrt(arr*mat));

[[ 14.14213562  28.28427125  42.42640687]
 [ 28.28427125 149.66629547  60.        ]]


task3

In [11]:


sales = np.array([
    [50, 65, 70, 60],   
    [80, 75, 90, 85],   
    [40, 55, 60, 65],   
        
])

print(sales)

print(sales[0]) #print first row

print(sales[:, 0:2])



[[50 65 70 60]
 [80 75 90 85]
 [40 55 60 65]]
[50 65 70 60]
[[50 65]
 [80 75]
 [40 55]]


task4

In [12]:
print(sales.reshape(2,6));

[[50 65 70 60 80 75]
 [90 85 40 55 60 65]]


In [13]:
print(sales.reshape(12));

[50 65 70 60 80 75 90 85 40 55 60 65]


In [17]:
import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(1,100,10);
print(x);

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


task5

In [20]:
arr=np.random.randint(1,20,12);
print(arr.reshape(3,4));

[[12  8 17  2]
 [ 9  5  7 14]
 [13  7  5 17]]


In [21]:
print(np.random.randint(1,100,5)); 

[60 38 61 88 62]
