#my first notebook (numpy)

In [4]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
#2d array
mat=np.array([[ 1,2,3],[4,5,6]])
print (mat)

[[1 2 3]
 [4 5 6]]


In [6]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.ones(5)


array([1., 1., 1., 1., 1.])

In [8]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [15]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

array properties

In [17]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

2
(2, 3)
6
int64


In [18]:
arr=np.array([10,20,30])
print(arr[0])
print(arr[-1])

10
30



1d slicing

In [19]:
print(arr[1:3])
print(arr[:2])

[20 30]
[10 20]


2d indexing & slicing


In [21]:
mat=np.array(([1,2,3],[4,5,6],[7,8,9]))
print (mat[0,1])
print(mat[1])

2
[4 5 6]


In [ ]:
print(mat[:,1]) #COLUMN 1

[2 5 8]


In [23]:
a=np.array([1,2,3])
b=a.copy()
b[0]=99
print(a)
print(b)

[1 2 3]
[99  2  3]


In [24]:
a=np.array([1,2,3])
b=a
b[0]=99
print(a)
#this logic is not safe

[99  2  3]


basic array operations (vector power)

In [25]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [26]:
print(a+10)
print(a*2)

[11 12 13]
[2 4 6]


unfus (universal functions)

In [27]:
arr=np.array([1,4,9,16])
print(np.sqrt(arr))
print(np.log(arr))
print(np.exp(arr))
print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))
print(np.sum(arr))
print(np.std(arr))

[1. 2. 3. 4.]
[0.         1.38629436 2.19722458 2.77258872]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
16
1
7.5
30
5.678908345800274


boolean indexing

In [ ]:
arr=np.array([10,20,30,40,50])
print(arr[arr>25])


[30 40 50]


In [29]:
print(arr>25)

[False False  True  True  True]


brodcasting rule

In [2]:
import numpy as np

In [3]:
#numpy automatically expands smaller arrays

arr=np.array([1,2,3,4])
print(arr+10)

[11 12 13 14]


In [4]:
mat=np.array([[1,2,3],[4,5,6]])
print(mat+10)

[[11 12 13]
 [14 15 16]]


In [5]:
row=np.array([1,2,3])
print(mat+row)

[[2 4 6]
 [5 7 9]]


In [ ]:
A=np.array([[1,2],[3,4]])
B=np.array([[1,2],[3,4]])
print(np.dot(A,B))


[[ 7 10]
 [15 22]]


In [8]:
print(A.T) #transpose

[[1 3]
 [2 4]]


Random Module

In [9]:
np.random.rand(5)

array([0.60805653, 0.80983953, 0.07001881, 0.60448489, 0.27429618])

In [ ]:
np.random.rand(3,3)

array([[0.92428985, 0.43740952, 0.0571688 ],
       [0.69779328, 0.35969543, 0.01383395],
       [0.89531772, 0.01319307, 0.47718194]])

In [11]:
np.random.randint(1,100,10)

array([95, 29, 81, 98, 66, 15, 87, 84,  7, 84], dtype=int32)

Reshaping array

In [12]:
arr=np.arange(12)
print(arr.reshape(3,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


axis in Numpy


In [14]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [15]:
print(np.sum(arr))

21


In [ ]:
print(np.sum(arr,axis=0)) #colum-wise

[5 7 9]


In [17]:
print(np.sum(arr,axis=1)) #row-wise

[ 6 15]


where in numpy

In [18]:
arr=np.array([10,-5,20,-3,15])

In [19]:
res=np.where(arr<0,0,arr)
print(res)

[10  0 20  0 15]


In [22]:
arr=np.array([1,2,3,4,5])

In [23]:
res=np.where(arr%2!=0,-1,arr)
print(res)

[-1  2 -1  4 -1]


In [27]:
marks=np.array([1,2,3,4,50])


In [28]:
stat=np.where(marks>=50,1,0)
print(stat)

[0 0 0 0 1]


In [29]:
data=np.array([10,20,30,40])

In [30]:
mean_val=np.mean(data)
result=np.where(data>mean_val,mean_val,data)
print(result)

[10. 20. 25. 25.]


1.create a id numpy array called cost containing the prices for the 3 items.


In [2]:
import numpy as np


In [3]:
cost=np.array([1500,3000,5000])
print(cost)

[1500 3000 5000]


In [1]:
import numpy as np